/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stdio.h>

#include "FreeRTOS.h"

#include "FreeRTOSConfig.h"

#include "task.h"

#include "led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)

  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."

#endif


void vLedTask(void *pvParam)

{

    uint16_t led_pin = ((uint16_t *)pvParam)[0];

    uint32_t delay_ms = ((uint16_t *)pvParam)[1];


    while (1)

    {

        led_toggle(led_pin);

        vTaskDelay(delay_ms / portTICK_RATE_MS);

    }


    vTaskDelete(NULL);

}


int main(void)

{

    led_init(LED_RED);

    led_init(LED_GREEN);

    led_init(LED_BLUE);

    led_init(LED_ORANGE);


    static uint16_t redParams[2] = {LED_RED, 4000};

    static uint16_t greenParams[2] = {LED_GREEN, 3000};

    static uint16_t blueParams[2] = {LED_BLUE, 2000};

    static uint16_t orangeParams[2] = {LED_ORANGE, 1000};


    xTaskCreate(vLedTask, "Red_LED_Task", configMINIMAL_STACK_SIZE, redParams, 4, NULL);

    xTaskCreate(vLedTask, "Green_LED_Task", configMINIMAL_STACK_SIZE, greenParams, 3, NULL);

    xTaskCreate(vLedTask, "Blue_LED_Task", configMINIMAL_STACK_SIZE, blueParams, 2, NULL);

    xTaskCreate(vLedTask, "Orange_LED_Task", configMINIMAL_STACK_SIZE, orangeParams, 1, NULL);


    vTaskStartScheduler();


    while (1);

}


