/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include"FreeRTOSConfig.h"
#include"FreeRTOS.h"
#include"task.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*void vMainTaskFunction(void * pvParam)
{
	while(1){
		// work
		led_toggle();
		vTaskDelay(1000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
*/


void vLedTask1(void *pvparam)
{
	while(1){
	led_toggle(LED_GREEN);
	vTaskDelay(1000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
void vLedTask2(void *pvparam)
{
	while(1){
	led_toggle(LED_ORANGE);
	vTaskDelay(2000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
void vLedTask3(void *pvparam)
{
	while(1){
	led_toggle(LED_RED);
	vTaskDelay(3000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
void vLedTask4(void *pvparam)
{
	while(1){
	led_toggle(LED_BLUE);
	vTaskDelay(4000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

int main(void)
{
	led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);
	led_init(LED_BLUE);

	xTaskCreate(vLedTask1, "Green_light", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vLedTask2, "ORANGE_light", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vLedTask3, "RED_light", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vLedTask4, "BLUE_light", configMINIMAL_STACK_SIZE, NULL, 4, NULL);

	vTaskStartScheduler();
	while(1);
}














